      # language: es
      Característica: Creación de Guías en Portal Corporativo
        Vertical: Delivery
        Producto: Hermes Portal - Creacion de Guias Portal Corporativo UI
        Release:
        Jira:
        Product Owner:
        QA Lead: Carlos Gonzalez

      @creacionGuias_COD_COLLET_corporativo
      Esquema del escenario: Portal Corporativo Guias COD
      Dado el usuario selecciona la url del portal de forza "<url>" y el titulo de la pagina es "<titulo>"
      Y el usuario selecciona el pais "<pais>"
      Y el usuario ingresa el codigo "<codigo>" el usuario "<usuario>" y su pass "<contrasenia>"
      Y el usuario selecciona la opcion pare crear guias
      Y datos corp para crear guia tipo "<tipo_guia>" collet "<collet>"
      Entonces el usuario inicia el proceso de creacion de guias

      Ejemplos:
      | Escenario               | url                               | titulo     | pais      | codigo | usuario      | contrasenia | tipo_guia       | collet |
      | COD-Collet-corporativo  | https://portal.forzadelivery.com/ | Hermes Web | Guatemala | 103492 | nidias.lucys | qaqaqaqa    | Servicio C.O.D. | true   |
      | COD-Credito-corporativo | https://portal.forzadelivery.com/ | Hermes Web | Guatemala | 103492 | nidias.lucys | qaqaqaqa    | Servicio C.O.D. | false  |

      @creacionGuias_STD_corporativo
      Esquema del escenario: Portal Corporativo Guias STD
      Dado el usuario selecciona la url del portal de forza "<url>" y el titulo de la pagina es "<titulo>"
      Y el usuario selecciona el pais "<pais>"
      Y el usuario ingresa el codigo "<codigo>" el usuario "<usuario>" y su pass "<contrasenia>"
      Y el usuario selecciona la opcion pare crear guias
      Y datos corp para crear guia tipo "<tipo_guia>" collet "<collet>"
      Entonces el usuario inicia el proceso de creacion de guias

      Ejemplos:
      | Escenario               | url                               | titulo     | pais      | codigo | usuario      | contrasenia | tipo_guia         | collet |
      | STD-Collet-corporativo  | https://portal.forzadelivery.com/ | Hermes Web | Guatemala | 103492 | nidias.lucys | qaqaqaqa    | Servicio Estándar | true   |
      | STD-Credito-corporativo | https://portal.forzadelivery.com/ | Hermes Web | Guatemala | 103492 | nidias.lucys | qaqaqaqa    | Servicio Estándar | false  |

      @servicio_devolucion_corporativo
      Esquema del escenario: Portal Corporativo Servicio de Devolucion
      Dado el usuario selecciona la url del portal de forza "<url>" y el titulo de la pagina es "<titulo>"
      Y el usuario selecciona el pais "<pais>"
      Y el usuario ingresa el codigo "<codigo>" el usuario "<usuario>" y su pass "<contrasenia>"
      Y el usuario selecciona la opcion pare crear guias
      Y datos para crear devolucion pais "<pais>" destino "<destino>" tipo "<tipo_guia>" entrega "<tipo_entrega>" cobro "<tipo_cobro>" referencia "<referencia_destino>" poblado "<poblado>" nombre "<nombre_contacto>" telefono "<telefono>" direccion "<direccion_remitente>"
      Entonces el usuario inicia el proceso de servicio de devolucion
      Y el usuario valida la guia de devolucion creada en mis envios

      @devolucion_gt
      Ejemplos: Guatemala
      | Escenario                              | url                                               | titulo     | pais        | codigo                        | usuario                         | contrasenia                         | destino             | tipo_guia         | tipo_entrega | tipo_cobro | referencia_destino          | poblado                                  | nombre_contacto                  | telefono                  | direccion_remitente                  |
      | gt_cartera_estandar_casa_credito       | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Guatemala   | ENV:DEVOLUCION_GT_CORP_CODIGO | ENV:DEVOLUCION_GT_CORP_USUARIO | ENV:DEVOLUCION_GT_CORP_CONTRASENIA | Cartera de Clientes | Servicio Estándar | Casa         | Crédito    | Aldea El Cruzadero Melchor de Mencos | -                               | -                                | -                         | -                                    |
      | gt_cartera_estandar_casa_collect       | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Guatemala   | ENV:DEVOLUCION_GT_CORP_CODIGO | ENV:DEVOLUCION_GT_CORP_USUARIO | ENV:DEVOLUCION_GT_CORP_CONTRASENIA | Cartera de Clientes | Servicio Estándar | Casa         | Collect    | Aldea El Cruzadero Melchor de Mencos | -                               | -                                | -                         | -                                    |
      | gt_cartera_estandar_oficina_credito    | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Guatemala   | ENV:DEVOLUCION_GT_CORP_CODIGO | ENV:DEVOLUCION_GT_CORP_USUARIO | ENV:DEVOLUCION_GT_CORP_CONTRASENIA | Cartera de Clientes | Servicio Estándar | Oficina      | Crédito    | Aldea El Cruzadero Melchor de Mencos | -                               | -                                | -                         | -                                    |
      | gt_cartera_estandar_oficina_collect    | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Guatemala   | ENV:DEVOLUCION_GT_CORP_CODIGO | ENV:DEVOLUCION_GT_CORP_USUARIO | ENV:DEVOLUCION_GT_CORP_CONTRASENIA | Cartera de Clientes | Servicio Estándar | Oficina      | Collect    | Aldea El Cruzadero Melchor de Mencos | -                               | -                                | -                         | -                                    |
      | gt_cartera_cod_casa_credito            | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Guatemala   | ENV:DEVOLUCION_GT_CORP_CODIGO | ENV:DEVOLUCION_GT_CORP_USUARIO | ENV:DEVOLUCION_GT_CORP_CONTRASENIA | Cartera de Clientes | Servicio C.O.D.   | Casa         | Crédito    | Aldea El Cruzadero Melchor de Mencos | -                               | -                                | -                         | -                                    |
      | gt_cartera_cod_casa_collect            | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Guatemala   | ENV:DEVOLUCION_GT_CORP_CODIGO | ENV:DEVOLUCION_GT_CORP_USUARIO | ENV:DEVOLUCION_GT_CORP_CONTRASENIA | Cartera de Clientes | Servicio C.O.D.   | Casa         | Collect    | Aldea El Cruzadero Melchor de Mencos | -                               | -                                | -                         | -                                    |
      | gt_cartera_cod_oficina_credito         | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Guatemala   | ENV:DEVOLUCION_GT_CORP_CODIGO | ENV:DEVOLUCION_GT_CORP_USUARIO | ENV:DEVOLUCION_GT_CORP_CONTRASENIA | Cartera de Clientes | Servicio C.O.D.   | Oficina      | Crédito    | Aldea El Cruzadero Melchor de Mencos | -                               | -                                | -                         | -                                    |
      | gt_cartera_cod_oficina_collect         | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Guatemala   | ENV:DEVOLUCION_GT_CORP_CODIGO | ENV:DEVOLUCION_GT_CORP_USUARIO | ENV:DEVOLUCION_GT_CORP_CONTRASENIA | Cartera de Clientes | Servicio C.O.D.   | Oficina      | Collect    | Aldea El Cruzadero Melchor de Mencos | -                               | -                                | -                         | -                                    |
      | gt_manual_estandar_casa_credito        | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Guatemala   | ENV:DEVOLUCION_GT_CORP_CODIGO | ENV:DEVOLUCION_GT_CORP_USUARIO | ENV:DEVOLUCION_GT_CORP_CONTRASENIA | Manual              | Servicio Estándar | Casa         | Crédito    | -                           | El Limon Norte, Chísec, Alta Verapaz    | ENV:DEVOLUCION_GT_NOMBRE_CONTACTO | ENV:DEVOLUCION_GT_TELEFONO | ENV:DEVOLUCION_GT_DIRECCION_REMITENTE |
      | gt_manual_estandar_casa_collect        | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Guatemala   | ENV:DEVOLUCION_GT_CORP_CODIGO | ENV:DEVOLUCION_GT_CORP_USUARIO | ENV:DEVOLUCION_GT_CORP_CONTRASENIA | Manual              | Servicio Estándar | Casa         | Collect    | -                           | El Limon Norte, Chísec, Alta Verapaz    | ENV:DEVOLUCION_GT_NOMBRE_CONTACTO | ENV:DEVOLUCION_GT_TELEFONO | ENV:DEVOLUCION_GT_DIRECCION_REMITENTE |
      | gt_manual_estandar_oficina_credito     | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Guatemala   | ENV:DEVOLUCION_GT_CORP_CODIGO | ENV:DEVOLUCION_GT_CORP_USUARIO | ENV:DEVOLUCION_GT_CORP_CONTRASENIA | Manual              | Servicio Estándar | Oficina      | Crédito    | -                           | El Limon Norte, Chísec, Alta Verapaz    | ENV:DEVOLUCION_GT_NOMBRE_CONTACTO | ENV:DEVOLUCION_GT_TELEFONO | ENV:DEVOLUCION_GT_DIRECCION_REMITENTE |
      | gt_manual_estandar_oficina_collect     | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Guatemala   | ENV:DEVOLUCION_GT_CORP_CODIGO | ENV:DEVOLUCION_GT_CORP_USUARIO | ENV:DEVOLUCION_GT_CORP_CONTRASENIA | Manual              | Servicio Estándar | Oficina      | Collect    | -                           | El Limon Norte, Chísec, Alta Verapaz    | ENV:DEVOLUCION_GT_NOMBRE_CONTACTO | ENV:DEVOLUCION_GT_TELEFONO | ENV:DEVOLUCION_GT_DIRECCION_REMITENTE |
      | gt_manual_cod_casa_credito             | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Guatemala   | ENV:DEVOLUCION_GT_CORP_CODIGO | ENV:DEVOLUCION_GT_CORP_USUARIO | ENV:DEVOLUCION_GT_CORP_CONTRASENIA | Manual              | Servicio C.O.D.   | Casa         | Crédito    | -                           | El Limon Norte, Chísec, Alta Verapaz    | ENV:DEVOLUCION_GT_NOMBRE_CONTACTO | ENV:DEVOLUCION_GT_TELEFONO | ENV:DEVOLUCION_GT_DIRECCION_REMITENTE |
      | gt_manual_cod_casa_collect             | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Guatemala   | ENV:DEVOLUCION_GT_CORP_CODIGO | ENV:DEVOLUCION_GT_CORP_USUARIO | ENV:DEVOLUCION_GT_CORP_CONTRASENIA | Manual              | Servicio C.O.D.   | Casa         | Collect    | -                           | El Limon Norte, Chísec, Alta Verapaz    | ENV:DEVOLUCION_GT_NOMBRE_CONTACTO | ENV:DEVOLUCION_GT_TELEFONO | ENV:DEVOLUCION_GT_DIRECCION_REMITENTE |
      | gt_manual_cod_oficina_credito          | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Guatemala   | ENV:DEVOLUCION_GT_CORP_CODIGO | ENV:DEVOLUCION_GT_CORP_USUARIO | ENV:DEVOLUCION_GT_CORP_CONTRASENIA | Manual              | Servicio C.O.D.   | Oficina      | Crédito    | -                           | El Limon Norte, Chísec, Alta Verapaz    | ENV:DEVOLUCION_GT_NOMBRE_CONTACTO | ENV:DEVOLUCION_GT_TELEFONO | ENV:DEVOLUCION_GT_DIRECCION_REMITENTE |
      | gt_manual_cod_oficina_collect          | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Guatemala   | ENV:DEVOLUCION_GT_CORP_CODIGO | ENV:DEVOLUCION_GT_CORP_USUARIO | ENV:DEVOLUCION_GT_CORP_CONTRASENIA | Manual              | Servicio C.O.D.   | Oficina      | Collect    | -                           | El Limon Norte, Chísec, Alta Verapaz    | ENV:DEVOLUCION_GT_NOMBRE_CONTACTO | ENV:DEVOLUCION_GT_TELEFONO | ENV:DEVOLUCION_GT_DIRECCION_REMITENTE |
      | gt_exc_estandar_casa_credito           | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Guatemala   | ENV:DEVOLUCION_GT_CORP_CODIGO | ENV:DEVOLUCION_GT_CORP_USUARIO | ENV:DEVOLUCION_GT_CORP_CONTRASENIA | EXC                 | Servicio Estándar | Casa         | Crédito    | EXPRESS CENTER CLUBFORZA    | -                                        | -                                | -                         | -                                    |
      | gt_exc_estandar_casa_collect           | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Guatemala   | ENV:DEVOLUCION_GT_CORP_CODIGO | ENV:DEVOLUCION_GT_CORP_USUARIO | ENV:DEVOLUCION_GT_CORP_CONTRASENIA | EXC                 | Servicio Estándar | Casa         | Collect    | EXPRESS CENTER CLUBFORZA    | -                                        | -                                | -                         | -                                    |
      | gt_exc_estandar_oficina_credito        | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Guatemala   | ENV:DEVOLUCION_GT_CORP_CODIGO | ENV:DEVOLUCION_GT_CORP_USUARIO | ENV:DEVOLUCION_GT_CORP_CONTRASENIA | EXC                 | Servicio Estándar | Oficina      | Crédito    | EXPRESS CENTER CLUBFORZA    | -                                        | -                                | -                         | -                                    |
      | gt_exc_estandar_oficina_collect        | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Guatemala   | ENV:DEVOLUCION_GT_CORP_CODIGO | ENV:DEVOLUCION_GT_CORP_USUARIO | ENV:DEVOLUCION_GT_CORP_CONTRASENIA | EXC                 | Servicio Estándar | Oficina      | Collect    | EXPRESS CENTER CLUBFORZA    | -                                        | -                                | -                         | -                                    |
      | gt_exc_cod_casa_credito                | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Guatemala   | ENV:DEVOLUCION_GT_CORP_CODIGO | ENV:DEVOLUCION_GT_CORP_USUARIO | ENV:DEVOLUCION_GT_CORP_CONTRASENIA | EXC                 | Servicio C.O.D.   | Casa         | Crédito    | EXPRESS CENTER CLUBFORZA    | -                                        | -                                | -                         | -                                    |
      | gt_exc_cod_casa_collect                | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Guatemala   | ENV:DEVOLUCION_GT_CORP_CODIGO | ENV:DEVOLUCION_GT_CORP_USUARIO | ENV:DEVOLUCION_GT_CORP_CONTRASENIA | EXC                 | Servicio C.O.D.   | Casa         | Collect    | EXPRESS CENTER CLUBFORZA    | -                                        | -                                | -                         | -                                    |
      | gt_exc_cod_oficina_credito             | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Guatemala   | ENV:DEVOLUCION_GT_CORP_CODIGO | ENV:DEVOLUCION_GT_CORP_USUARIO | ENV:DEVOLUCION_GT_CORP_CONTRASENIA | EXC                 | Servicio C.O.D.   | Oficina      | Crédito    | EXPRESS CENTER CLUBFORZA    | -                                        | -                                | -                         | -                                    |
      | gt_exc_cod_oficina_collect             | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Guatemala   | ENV:DEVOLUCION_GT_CORP_CODIGO | ENV:DEVOLUCION_GT_CORP_USUARIO | ENV:DEVOLUCION_GT_CORP_CONTRASENIA | EXC                 | Servicio C.O.D.   | Oficina      | Collect    | EXPRESS CENTER CLUBFORZA    | -                                        | -                                | -                         | -                                    |

      @devolucion_hn
      Ejemplos: Honduras
      | Escenario                              | url                                               | titulo     | pais        | codigo                        | usuario                         | contrasenia                         | destino             | tipo_guia         | tipo_entrega | tipo_cobro | referencia_destino          | poblado                                  | nombre_contacto                  | telefono                  | direccion_remitente                  |
      | hn_cartera_estandar_casa_credito       | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Honduras    | ENV:DEVOLUCION_HN_CORP_CODIGO | ENV:DEVOLUCION_HN_CORP_USUARIO | ENV:DEVOLUCION_HN_CORP_CONTRASENIA | Cartera de Clientes | Servicio Estándar | Casa         | Crédito    | Ave. 12-3 zona 2            | -                                        | -                                | -                         | -                                    |
      | hn_cartera_estandar_casa_collect       | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Honduras    | ENV:DEVOLUCION_HN_CORP_CODIGO | ENV:DEVOLUCION_HN_CORP_USUARIO | ENV:DEVOLUCION_HN_CORP_CONTRASENIA | Cartera de Clientes | Servicio Estándar | Casa         | Collect    | Ave. 12-3 zona 2            | -                                        | -                                | -                         | -                                    |
      | hn_cartera_estandar_oficina_credito    | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Honduras    | ENV:DEVOLUCION_HN_CORP_CODIGO | ENV:DEVOLUCION_HN_CORP_USUARIO | ENV:DEVOLUCION_HN_CORP_CONTRASENIA | Cartera de Clientes | Servicio Estándar | Oficina      | Crédito    | Ave. 12-3 zona 2            | -                                        | -                                | -                         | -                                    |
      | hn_cartera_estandar_oficina_collect    | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Honduras    | ENV:DEVOLUCION_HN_CORP_CODIGO | ENV:DEVOLUCION_HN_CORP_USUARIO | ENV:DEVOLUCION_HN_CORP_CONTRASENIA | Cartera de Clientes | Servicio Estándar | Oficina      | Collect    | Ave. 12-3 zona 2            | -                                        | -                                | -                         | -                                    |
      | hn_cartera_cod_casa_credito            | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Honduras    | ENV:DEVOLUCION_HN_CORP_CODIGO | ENV:DEVOLUCION_HN_CORP_USUARIO | ENV:DEVOLUCION_HN_CORP_CONTRASENIA | Cartera de Clientes | Servicio C.O.D.   | Casa         | Crédito    | Ave. 12-3 zona 2            | -                                        | -                                | -                         | -                                    |
      | hn_cartera_cod_casa_collect            | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Honduras    | ENV:DEVOLUCION_HN_CORP_CODIGO | ENV:DEVOLUCION_HN_CORP_USUARIO | ENV:DEVOLUCION_HN_CORP_CONTRASENIA | Cartera de Clientes | Servicio C.O.D.   | Casa         | Collect    | Ave. 12-3 zona 2            | -                                        | -                                | -                         | -                                    |
      | hn_cartera_cod_oficina_credito         | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Honduras    | ENV:DEVOLUCION_HN_CORP_CODIGO | ENV:DEVOLUCION_HN_CORP_USUARIO | ENV:DEVOLUCION_HN_CORP_CONTRASENIA | Cartera de Clientes | Servicio C.O.D.   | Oficina      | Crédito    | Ave. 12-3 zona 2            | -                                        | -                                | -                         | -                                    |
      | hn_cartera_cod_oficina_collect         | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Honduras    | ENV:DEVOLUCION_HN_CORP_CODIGO | ENV:DEVOLUCION_HN_CORP_USUARIO | ENV:DEVOLUCION_HN_CORP_CONTRASENIA | Cartera de Clientes | Servicio C.O.D.   | Oficina      | Collect    | Ave. 12-3 zona 2            | -                                        | -                                | -                         | -                                    |
      | hn_manual_estandar_casa_credito        | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Honduras    | ENV:DEVOLUCION_HN_CORP_CODIGO | ENV:DEVOLUCION_HN_CORP_USUARIO | ENV:DEVOLUCION_HN_CORP_CONTRASENIA | Manual              | Servicio Estándar | Casa         | Crédito    | -                           | Col. La Alhambra, LA CEIBA, Atlántida   | ENV:DEVOLUCION_HN_NOMBRE_CONTACTO | ENV:DEVOLUCION_HN_TELEFONO | ENV:DEVOLUCION_HN_DIRECCION_REMITENTE |
      | hn_manual_estandar_casa_collect        | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Honduras    | ENV:DEVOLUCION_HN_CORP_CODIGO | ENV:DEVOLUCION_HN_CORP_USUARIO | ENV:DEVOLUCION_HN_CORP_CONTRASENIA | Manual              | Servicio Estándar | Casa         | Collect    | -                           | Col. La Alhambra, LA CEIBA, Atlántida   | ENV:DEVOLUCION_HN_NOMBRE_CONTACTO | ENV:DEVOLUCION_HN_TELEFONO | ENV:DEVOLUCION_HN_DIRECCION_REMITENTE |
      | hn_manual_estandar_oficina_credito     | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Honduras    | ENV:DEVOLUCION_HN_CORP_CODIGO | ENV:DEVOLUCION_HN_CORP_USUARIO | ENV:DEVOLUCION_HN_CORP_CONTRASENIA | Manual              | Servicio Estándar | Oficina      | Crédito    | -                           | Col. La Alhambra, LA CEIBA, Atlántida   | ENV:DEVOLUCION_HN_NOMBRE_CONTACTO | ENV:DEVOLUCION_HN_TELEFONO | ENV:DEVOLUCION_HN_DIRECCION_REMITENTE |
      | hn_manual_estandar_oficina_collect     | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Honduras    | ENV:DEVOLUCION_HN_CORP_CODIGO | ENV:DEVOLUCION_HN_CORP_USUARIO | ENV:DEVOLUCION_HN_CORP_CONTRASENIA | Manual              | Servicio Estándar | Oficina      | Collect    | -                           | Col. La Alhambra, LA CEIBA, Atlántida   | ENV:DEVOLUCION_HN_NOMBRE_CONTACTO | ENV:DEVOLUCION_HN_TELEFONO | ENV:DEVOLUCION_HN_DIRECCION_REMITENTE |
      | hn_manual_cod_casa_credito             | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Honduras    | ENV:DEVOLUCION_HN_CORP_CODIGO | ENV:DEVOLUCION_HN_CORP_USUARIO | ENV:DEVOLUCION_HN_CORP_CONTRASENIA | Manual              | Servicio C.O.D.   | Casa         | Crédito    | -                           | Col. La Alhambra, LA CEIBA, Atlántida   | ENV:DEVOLUCION_HN_NOMBRE_CONTACTO | ENV:DEVOLUCION_HN_TELEFONO | ENV:DEVOLUCION_HN_DIRECCION_REMITENTE |
      | hn_manual_cod_casa_collect             | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Honduras    | ENV:DEVOLUCION_HN_CORP_CODIGO | ENV:DEVOLUCION_HN_CORP_USUARIO | ENV:DEVOLUCION_HN_CORP_CONTRASENIA | Manual              | Servicio C.O.D.   | Casa         | Collect    | -                           | Col. La Alhambra, LA CEIBA, Atlántida   | ENV:DEVOLUCION_HN_NOMBRE_CONTACTO | ENV:DEVOLUCION_HN_TELEFONO | ENV:DEVOLUCION_HN_DIRECCION_REMITENTE |
      | hn_manual_cod_oficina_credito          | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Honduras    | ENV:DEVOLUCION_HN_CORP_CODIGO | ENV:DEVOLUCION_HN_CORP_USUARIO | ENV:DEVOLUCION_HN_CORP_CONTRASENIA | Manual              | Servicio C.O.D.   | Oficina      | Crédito    | -                           | Col. La Alhambra, LA CEIBA, Atlántida   | ENV:DEVOLUCION_HN_NOMBRE_CONTACTO | ENV:DEVOLUCION_HN_TELEFONO | ENV:DEVOLUCION_HN_DIRECCION_REMITENTE |
      | hn_manual_cod_oficina_collect          | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Honduras    | ENV:DEVOLUCION_HN_CORP_CODIGO | ENV:DEVOLUCION_HN_CORP_USUARIO | ENV:DEVOLUCION_HN_CORP_CONTRASENIA | Manual              | Servicio C.O.D.   | Oficina      | Collect    | -                           | Col. La Alhambra, LA CEIBA, Atlántida   | ENV:DEVOLUCION_HN_NOMBRE_CONTACTO | ENV:DEVOLUCION_HN_TELEFONO | ENV:DEVOLUCION_HN_DIRECCION_REMITENTE |
      | hn_exc_estandar_casa_credito           | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Honduras    | ENV:DEVOLUCION_HN_CORP_CODIGO | ENV:DEVOLUCION_HN_CORP_USUARIO | ENV:DEVOLUCION_HN_CORP_CONTRASENIA | EXC                 | Servicio Estándar | Casa         | Crédito    | FD EXC PLAZA PREMIER        | -                                        | -                                | -                         | -                                    |
      | hn_exc_estandar_casa_collect           | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Honduras    | ENV:DEVOLUCION_HN_CORP_CODIGO | ENV:DEVOLUCION_HN_CORP_USUARIO | ENV:DEVOLUCION_HN_CORP_CONTRASENIA | EXC                 | Servicio Estándar | Casa         | Collect    | FD EXC PLAZA PREMIER        | -                                        | -                                | -                         | -                                    |
      | hn_exc_estandar_oficina_credito        | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Honduras    | ENV:DEVOLUCION_HN_CORP_CODIGO | ENV:DEVOLUCION_HN_CORP_USUARIO | ENV:DEVOLUCION_HN_CORP_CONTRASENIA | EXC                 | Servicio Estándar | Oficina      | Crédito    | FD EXC PLAZA PREMIER        | -                                        | -                                | -                         | -                                    |
      | hn_exc_estandar_oficina_collect        | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Honduras    | ENV:DEVOLUCION_HN_CORP_CODIGO | ENV:DEVOLUCION_HN_CORP_USUARIO | ENV:DEVOLUCION_HN_CORP_CONTRASENIA | EXC                 | Servicio Estándar | Oficina      | Collect    | FD EXC PLAZA PREMIER        | -                                        | -                                | -                         | -                                    |
      | hn_exc_cod_casa_credito                | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Honduras    | ENV:DEVOLUCION_HN_CORP_CODIGO | ENV:DEVOLUCION_HN_CORP_USUARIO | ENV:DEVOLUCION_HN_CORP_CONTRASENIA | EXC                 | Servicio C.O.D.   | Casa         | Crédito    | FD EXC PLAZA PREMIER        | -                                        | -                                | -                         | -                                    |
      | hn_exc_cod_casa_collect                | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Honduras    | ENV:DEVOLUCION_HN_CORP_CODIGO | ENV:DEVOLUCION_HN_CORP_USUARIO | ENV:DEVOLUCION_HN_CORP_CONTRASENIA | EXC                 | Servicio C.O.D.   | Casa         | Collect    | FD EXC PLAZA PREMIER        | -                                        | -                                | -                         | -                                    |
      | hn_exc_cod_oficina_credito             | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Honduras    | ENV:DEVOLUCION_HN_CORP_CODIGO | ENV:DEVOLUCION_HN_CORP_USUARIO | ENV:DEVOLUCION_HN_CORP_CONTRASENIA | EXC                 | Servicio C.O.D.   | Oficina      | Crédito    | FD EXC PLAZA PREMIER        | -                                        | -                                | -                         | -                                    |
      | hn_exc_cod_oficina_collect             | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | Honduras    | ENV:DEVOLUCION_HN_CORP_CODIGO | ENV:DEVOLUCION_HN_CORP_USUARIO | ENV:DEVOLUCION_HN_CORP_CONTRASENIA | EXC                 | Servicio C.O.D.   | Oficina      | Collect    | FD EXC PLAZA PREMIER        | -                                        | -                                | -                         | -                                    |

      @devolucion_sv
      Ejemplos: El Salvador
      | Escenario                              | url                                               | titulo     | pais        | codigo                        | usuario                         | contrasenia                         | destino             | tipo_guia         | tipo_entrega | tipo_cobro | referencia_destino          | poblado                                  | nombre_contacto                  | telefono                  | direccion_remitente                  |
      | sv_cartera_estandar_casa_credito       | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | El Salvador | ENV:DEVOLUCION_SV_CORP_CODIGO | ENV:DEVOLUCION_SV_CORP_USUARIO | ENV:DEVOLUCION_SV_CORP_CONTRASENIA | Cartera de Clientes | Servicio Estándar | Casa         | Crédito    | Ahuachapan zona 2           | -                                        | -                                | -                         | -                                    |
      | sv_cartera_estandar_casa_collect       | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | El Salvador | ENV:DEVOLUCION_SV_CORP_CODIGO | ENV:DEVOLUCION_SV_CORP_USUARIO | ENV:DEVOLUCION_SV_CORP_CONTRASENIA | Cartera de Clientes | Servicio Estándar | Casa         | Collect    | Ahuachapan zona 2           | -                                        | -                                | -                         | -                                    |
      | sv_cartera_estandar_oficina_credito    | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | El Salvador | ENV:DEVOLUCION_SV_CORP_CODIGO | ENV:DEVOLUCION_SV_CORP_USUARIO | ENV:DEVOLUCION_SV_CORP_CONTRASENIA | Cartera de Clientes | Servicio Estándar | Oficina      | Crédito    | Ahuachapan zona 2           | -                                        | -                                | -                         | -                                    |
      | sv_cartera_estandar_oficina_collect    | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | El Salvador | ENV:DEVOLUCION_SV_CORP_CODIGO | ENV:DEVOLUCION_SV_CORP_USUARIO | ENV:DEVOLUCION_SV_CORP_CONTRASENIA | Cartera de Clientes | Servicio Estándar | Oficina      | Collect    | Ahuachapan zona 2           | -                                        | -                                | -                         | -                                    |
      | sv_cartera_cod_casa_credito            | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | El Salvador | ENV:DEVOLUCION_SV_CORP_CODIGO | ENV:DEVOLUCION_SV_CORP_USUARIO | ENV:DEVOLUCION_SV_CORP_CONTRASENIA | Cartera de Clientes | Servicio C.O.D.   | Casa         | Crédito    | Ahuachapan zona 2           | -                                        | -                                | -                         | -                                    |
      | sv_cartera_cod_casa_collect            | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | El Salvador | ENV:DEVOLUCION_SV_CORP_CODIGO | ENV:DEVOLUCION_SV_CORP_USUARIO | ENV:DEVOLUCION_SV_CORP_CONTRASENIA | Cartera de Clientes | Servicio C.O.D.   | Casa         | Collect    | Ahuachapan zona 2           | -                                        | -                                | -                         | -                                    |
      | sv_cartera_cod_oficina_credito         | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | El Salvador | ENV:DEVOLUCION_SV_CORP_CODIGO | ENV:DEVOLUCION_SV_CORP_USUARIO | ENV:DEVOLUCION_SV_CORP_CONTRASENIA | Cartera de Clientes | Servicio C.O.D.   | Oficina      | Crédito    | Ahuachapan zona 2           | -                                        | -                                | -                         | -                                    |
      | sv_cartera_cod_oficina_collect         | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | El Salvador | ENV:DEVOLUCION_SV_CORP_CODIGO | ENV:DEVOLUCION_SV_CORP_USUARIO | ENV:DEVOLUCION_SV_CORP_CONTRASENIA | Cartera de Clientes | Servicio C.O.D.   | Oficina      | Collect    | Ahuachapan zona 2           | -                                        | -                                | -                         | -                                    |
      | sv_manual_estandar_casa_credito        | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | El Salvador | ENV:DEVOLUCION_SV_CORP_CODIGO | ENV:DEVOLUCION_SV_CORP_USUARIO | ENV:DEVOLUCION_SV_CORP_CONTRASENIA | Manual              | Servicio Estándar | Casa         | Crédito    | -                           | EL ROBLE, Ahuachapán, Ahuachapán        | ENV:DEVOLUCION_SV_NOMBRE_CONTACTO | ENV:DEVOLUCION_SV_TELEFONO | ENV:DEVOLUCION_SV_DIRECCION_REMITENTE |
      | sv_manual_estandar_casa_collect        | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | El Salvador | ENV:DEVOLUCION_SV_CORP_CODIGO | ENV:DEVOLUCION_SV_CORP_USUARIO | ENV:DEVOLUCION_SV_CORP_CONTRASENIA | Manual              | Servicio Estándar | Casa         | Collect    | -                           | EL ROBLE, Ahuachapán, Ahuachapán        | ENV:DEVOLUCION_SV_NOMBRE_CONTACTO | ENV:DEVOLUCION_SV_TELEFONO | ENV:DEVOLUCION_SV_DIRECCION_REMITENTE |
      | sv_manual_estandar_oficina_credito     | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | El Salvador | ENV:DEVOLUCION_SV_CORP_CODIGO | ENV:DEVOLUCION_SV_CORP_USUARIO | ENV:DEVOLUCION_SV_CORP_CONTRASENIA | Manual              | Servicio Estándar | Oficina      | Crédito    | -                           | EL ROBLE, Ahuachapán, Ahuachapán        | ENV:DEVOLUCION_SV_NOMBRE_CONTACTO | ENV:DEVOLUCION_SV_TELEFONO | ENV:DEVOLUCION_SV_DIRECCION_REMITENTE |
      | sv_manual_estandar_oficina_collect     | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | El Salvador | ENV:DEVOLUCION_SV_CORP_CODIGO | ENV:DEVOLUCION_SV_CORP_USUARIO | ENV:DEVOLUCION_SV_CORP_CONTRASENIA | Manual              | Servicio Estándar | Oficina      | Collect    | -                           | EL ROBLE, Ahuachapán, Ahuachapán        | ENV:DEVOLUCION_SV_NOMBRE_CONTACTO | ENV:DEVOLUCION_SV_TELEFONO | ENV:DEVOLUCION_SV_DIRECCION_REMITENTE |
      | sv_manual_cod_casa_credito             | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | El Salvador | ENV:DEVOLUCION_SV_CORP_CODIGO | ENV:DEVOLUCION_SV_CORP_USUARIO | ENV:DEVOLUCION_SV_CORP_CONTRASENIA | Manual              | Servicio C.O.D.   | Casa         | Crédito    | -                           | EL ROBLE, Ahuachapán, Ahuachapán        | ENV:DEVOLUCION_SV_NOMBRE_CONTACTO | ENV:DEVOLUCION_SV_TELEFONO | ENV:DEVOLUCION_SV_DIRECCION_REMITENTE |
      | sv_manual_cod_casa_collect             | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | El Salvador | ENV:DEVOLUCION_SV_CORP_CODIGO | ENV:DEVOLUCION_SV_CORP_USUARIO | ENV:DEVOLUCION_SV_CORP_CONTRASENIA | Manual              | Servicio C.O.D.   | Casa         | Collect    | -                           | EL ROBLE, Ahuachapán, Ahuachapán        | ENV:DEVOLUCION_SV_NOMBRE_CONTACTO | ENV:DEVOLUCION_SV_TELEFONO | ENV:DEVOLUCION_SV_DIRECCION_REMITENTE |
      | sv_manual_cod_oficina_credito          | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | El Salvador | ENV:DEVOLUCION_SV_CORP_CODIGO | ENV:DEVOLUCION_SV_CORP_USUARIO | ENV:DEVOLUCION_SV_CORP_CONTRASENIA | Manual              | Servicio C.O.D.   | Oficina      | Crédito    | -                           | EL ROBLE, Ahuachapán, Ahuachapán        | ENV:DEVOLUCION_SV_NOMBRE_CONTACTO | ENV:DEVOLUCION_SV_TELEFONO | ENV:DEVOLUCION_SV_DIRECCION_REMITENTE |
      | sv_manual_cod_oficina_collect          | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | El Salvador | ENV:DEVOLUCION_SV_CORP_CODIGO | ENV:DEVOLUCION_SV_CORP_USUARIO | ENV:DEVOLUCION_SV_CORP_CONTRASENIA | Manual              | Servicio C.O.D.   | Oficina      | Collect    | -                           | EL ROBLE, Ahuachapán, Ahuachapán        | ENV:DEVOLUCION_SV_NOMBRE_CONTACTO | ENV:DEVOLUCION_SV_TELEFONO | ENV:DEVOLUCION_SV_DIRECCION_REMITENTE |
      | sv_exc_estandar_casa_credito           | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | El Salvador | ENV:DEVOLUCION_SV_CORP_CODIGO | ENV:DEVOLUCION_SV_CORP_USUARIO | ENV:DEVOLUCION_SV_CORP_CONTRASENIA | EXC                 | Servicio Estándar | Casa         | Crédito    | FD EXC SAN SALVADOR ESTE    | -                                        | -                                | -                         | -                                    |
      | sv_exc_estandar_casa_collect           | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | El Salvador | ENV:DEVOLUCION_SV_CORP_CODIGO | ENV:DEVOLUCION_SV_CORP_USUARIO | ENV:DEVOLUCION_SV_CORP_CONTRASENIA | EXC                 | Servicio Estándar | Casa         | Collect    | FD EXC SAN SALVADOR ESTE    | -                                        | -                                | -                         | -                                    |
      | sv_exc_estandar_oficina_credito        | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | El Salvador | ENV:DEVOLUCION_SV_CORP_CODIGO | ENV:DEVOLUCION_SV_CORP_USUARIO | ENV:DEVOLUCION_SV_CORP_CONTRASENIA | EXC                 | Servicio Estándar | Oficina      | Crédito    | FD EXC SAN SALVADOR ESTE    | -                                        | -                                | -                         | -                                    |
      | sv_exc_estandar_oficina_collect        | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | El Salvador | ENV:DEVOLUCION_SV_CORP_CODIGO | ENV:DEVOLUCION_SV_CORP_USUARIO | ENV:DEVOLUCION_SV_CORP_CONTRASENIA | EXC                 | Servicio Estándar | Oficina      | Collect    | FD EXC SAN SALVADOR ESTE    | -                                        | -                                | -                         | -                                    |
      | sv_exc_cod_casa_credito                | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | El Salvador | ENV:DEVOLUCION_SV_CORP_CODIGO | ENV:DEVOLUCION_SV_CORP_USUARIO | ENV:DEVOLUCION_SV_CORP_CONTRASENIA | EXC                 | Servicio C.O.D.   | Casa         | Crédito    | FD EXC SAN SALVADOR ESTE    | -                                        | -                                | -                         | -                                    |
      | sv_exc_cod_casa_collect                | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | El Salvador | ENV:DEVOLUCION_SV_CORP_CODIGO | ENV:DEVOLUCION_SV_CORP_USUARIO | ENV:DEVOLUCION_SV_CORP_CONTRASENIA | EXC                 | Servicio C.O.D.   | Casa         | Collect    | FD EXC SAN SALVADOR ESTE    | -                                        | -                                | -                         | -                                    |
      | sv_exc_cod_oficina_credito             | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | El Salvador | ENV:DEVOLUCION_SV_CORP_CODIGO | ENV:DEVOLUCION_SV_CORP_USUARIO | ENV:DEVOLUCION_SV_CORP_CONTRASENIA | EXC                 | Servicio C.O.D.   | Oficina      | Crédito    | FD EXC SAN SALVADOR ESTE    | -                                        | -                                | -                         | -                                    |
      | sv_exc_cod_oficina_collect             | https://qa-portal.forzadeliveryexpress.com/login | Hermes Web | El Salvador | ENV:DEVOLUCION_SV_CORP_CODIGO | ENV:DEVOLUCION_SV_CORP_USUARIO | ENV:DEVOLUCION_SV_CORP_CONTRASENIA | EXC                 | Servicio C.O.D.   | Oficina      | Collect    | FD EXC SAN SALVADOR ESTE    | -                                        | -                                | -                         | -                                    |
